# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>

sudo: false
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - zlib1g-dev
script:
 - make clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" make V=1

