sudo: false
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - zlib1g-dev
script:
 - make clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" make V=1

matrix:
  include:
    - os: linux
      language: minimal
      services:
      - docker
      env:
      - REUSE_TEST=1
      before_install:
      - docker pull fsfe/reuse:latest
      - docker run --name reuse -v ${TRAVIS_BUILD_DIR}:/repo fsfe/reuse /bin/sh -c "cd /repo; reuse lint"
      script:
      - true
